Skip SQL tests if tarantool version < 2.0.0
Problem: all SQL-related tests fail with the following error
if tarantool < 2.0.0 is used:

    tarantool.error.DatabaseError: (48, 'Unknown request type 11')

Tarantool supports SQL-related stuff only since the 2.0.0 version.
So this patch adds a special decorator that will skip the test if
tarantool version < 2.0.0 is used.

Fixes #194